# Generated by Django 4.1.2 on 2022-10-19 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('body', models.TextField()),
                ('web', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='Bogotá', max_length=80, null=True)),
                ('state', models.CharField(blank=True, default='Bogotá D.C.', max_length=80, null=True)),
                ('country', models.CharField(blank=True, default='Colombia', max_length=80, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('organiza', models.CharField(blank=True, max_length=100, null=True)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('picture', django_resized.forms.ResizedImageField(blank=True, crop=None, default='eventos/evento.png', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[800, 600], upload_to='eventos')),
                ('flayer', django_resized.forms.ResizedImageField(blank=True, crop=None, default='eventos/flayer.png', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1000, 1400], upload_to='eventos')),
                ('banner', django_resized.forms.ResizedImageField(blank=True, crop=None, default='eventos/banner.png', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1000, 240], upload_to='eventos')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_add'],
            },
        ),
    ]
