# Generated by Django 4.1.2 on 2022-10-20 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='slug',
        ),
    ]
