# Generated by Django 4.1.2 on 2022-10-17 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('encargado', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('summary', models.CharField(blank=True, max_length=1600, null=True)),
                ('information', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('Persona', 'Persona'), ('Empresa', 'Empresa'), ('Fundacion', 'Fundacion'), ('Comunidad', 'Comunidad'), ('Organizacion', 'Organizacion'), ('Universidad', 'Universidad')], default='Comunidad', max_length=50, null=True)),
                ('longitud', models.CharField(max_length=100)),
                ('latitud', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, default='Bogotá', max_length=80, null=True)),
                ('state', models.CharField(blank=True, default='Bogotá D.C.', max_length=80, null=True)),
                ('country', models.CharField(blank=True, default='Colombia', max_length=80, null=True)),
                ('twitter', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('telegram', models.CharField(max_length=100)),
                ('slack', models.CharField(max_length=100)),
                ('googlePlus', models.CharField(max_length=100)),
                ('medium', models.CharField(max_length=100)),
                ('meetup', models.CharField(max_length=100)),
                ('web', models.CharField(max_length=100)),
                ('dob', models.DateField(auto_now_add=True)),
                ('Logo', models.ImageField(default='MEDIA/comunity/default.png', upload_to='img/comunity')),
                ('image', models.ImageField(default='MEDIA/comunity/default.png', upload_to='img/comunity')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('encargado', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('summary', models.CharField(blank=True, max_length=1600, null=True)),
                ('information', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('Persona', 'Persona'), ('Empresa', 'Empresa'), ('Fundacion', 'Fundacion'), ('Comunidad', 'Comunidad'), ('Organizacion', 'Organizacion'), ('Universidad', 'Universidad')], default='Empresa', max_length=50, null=True)),
                ('longitud', models.CharField(max_length=100)),
                ('latitud', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, default='Bogotá', max_length=80, null=True)),
                ('state', models.CharField(blank=True, default='Bogotá D.C.', max_length=80, null=True)),
                ('country', models.CharField(blank=True, default='Colombia', max_length=80, null=True)),
                ('twitter', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('telegram', models.CharField(max_length=100)),
                ('slack', models.CharField(max_length=100)),
                ('googlePlus', models.CharField(max_length=100)),
                ('medium', models.CharField(max_length=100)),
                ('meetup', models.CharField(max_length=100)),
                ('web', models.CharField(max_length=100)),
                ('dob', models.DateField(auto_now_add=True)),
                ('Logo', models.ImageField(default='MEDIA/companies/default.png', upload_to='img/companies')),
                ('image', models.ImageField(default='MEDIA/companies/default.png', upload_to='img/companies')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('sharePhone', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, choices=[('Persona', 'Persona'), ('Empresa', 'Empresa'), ('Fundacion', 'Fundacion'), ('Comunidad', 'Comunidad'), ('Organizacion', 'Organizacion'), ('Universidad', 'Universidad')], default='Persona', max_length=50, null=True)),
                ('city', models.CharField(blank=True, default='Bogotá', max_length=80, null=True)),
                ('state', models.CharField(blank=True, default='Bogotá D.C.', max_length=80, null=True)),
                ('country', models.CharField(blank=True, default='Colombia', max_length=80, null=True)),
                ('summary', models.CharField(blank=True, max_length=1600, null=True)),
                ('information', models.TextField()),
                ('github', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('telegram', models.CharField(max_length=100)),
                ('slack', models.CharField(max_length=100)),
                ('googlePlus', models.CharField(max_length=100)),
                ('medium', models.CharField(max_length=100)),
                ('meetup', models.CharField(max_length=100)),
                ('web', models.CharField(max_length=100)),
                ('dob', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(default='MEDIA/pythonistas/default.png', upload_to='img/pythonistas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
